// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-DCW1rGXdBS0reVOI40ow7_0HZdJbPU',
    appId: '1:877190353697:web:fc7e0eee360077edb36460',
    messagingSenderId: '877190353697',
    projectId: 'blogvlog-b3b09',
    authDomain: 'blogvlog-b3b09.firebaseapp.com',
    storageBucket: 'blogvlog-b3b09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Bt9iDBtNzCCLuePg8AN-ByrWuEVRgFE',
    appId: '1:877190353697:android:d556e1b4c36614e9b36460',
    messagingSenderId: '877190353697',
    projectId: 'blogvlog-b3b09',
    storageBucket: 'blogvlog-b3b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fY9v7RxRc6hRY-3eWHFUKNOKN6wzHBA',
    appId: '1:877190353697:ios:32e5f4e109f58abab36460',
    messagingSenderId: '877190353697',
    projectId: 'blogvlog-b3b09',
    storageBucket: 'blogvlog-b3b09.appspot.com',
    iosBundleId: 'com.example.blogVlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fY9v7RxRc6hRY-3eWHFUKNOKN6wzHBA',
    appId: '1:877190353697:ios:32e5f4e109f58abab36460',
    messagingSenderId: '877190353697',
    projectId: 'blogvlog-b3b09',
    storageBucket: 'blogvlog-b3b09.appspot.com',
    iosBundleId: 'com.example.blogVlog',
  );
}
